import { Dimensions, Platform, StyleSheet } from 'react-native';
import { COLORS } from '../../src/constants';

const { width } = Dimensions.get('window');
const OVAL_WIDTH = width * 0.62;
const OVAL_HEIGHT = OVAL_WIDTH * 1.35;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  bgCircle1: {
    position: 'absolute',
    top: -40,
    right: -60,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(108, 92, 231, 0.08)',
  },
  bgCircle2: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(0, 206, 201, 0.06)',
  },
  // Permission screen
  permissionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  permissionIconBg: {
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: 'rgba(108, 92, 231, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(108, 92, 231, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 28,
  },
  permissionTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: COLORS.text,
    marginBottom: 12,
  },
  permissionText: {
    fontSize: 15,
    color: COLORS.textMuted,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 32,
  },
  permissionBtn: {
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    paddingHorizontal: 48,
    borderRadius: 16,
  },
  permissionBtnText: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
  },
  // Camera view
  cameraView: {
    flex: 1,
    backgroundColor: '#0D0D1E',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraOverlayTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 140,
    backgroundColor: 'rgba(10, 10, 26, 0.85)',
  },
  cameraOverlayBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 200,
    backgroundColor: 'rgba(10, 10, 26, 0.9)',
  },
  gridContainer: {
    ...(StyleSheet.absoluteFill as object),
  },
  gridLineH: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(108, 92, 231, 0.04)',
  },
  gridLineV: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(108, 92, 231, 0.04)',
  },
  ovalContainer: {
    width: OVAL_WIDTH + 20,
    height: OVAL_HEIGHT + 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ovalGuide: {
    width: OVAL_WIDTH,
    height: OVAL_HEIGHT,
    borderRadius: OVAL_WIDTH / 2,
    borderWidth: 2.5,
    borderColor: 'rgba(108, 92, 231, 0.5)',
    backgroundColor: 'rgba(108, 92, 231, 0.03)',
  },
  ovalGuideCapturing: {
    borderColor: COLORS.accent,
    backgroundColor: 'rgba(0, 206, 201, 0.05)',
  },
  cornerMarker: {
    position: 'absolute',
    width: 24,
    height: 24,
    borderColor: COLORS.primary,
  },
  cornerTL: {
    top: 0,
    left: 0,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderTopLeftRadius: 8,
  },
  cornerTR: {
    top: 0,
    right: 0,
    borderTopWidth: 3,
    borderRightWidth: 3,
    borderTopRightRadius: 8,
  },
  cornerBL: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderBottomLeftRadius: 8,
  },
  cornerBR: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderBottomRightRadius: 8,
  },
  guideTextContainer: {
    position: 'absolute',
    bottom: 220,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  guideText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    fontWeight: '500',
    backgroundColor: 'rgba(10, 10, 26, 0.6)',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    overflow: 'hidden',
  },
  // Top bar
  topBar: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 60 : 45,
    left: 20,
    right: 20,
    zIndex: 10,
  },
  topBarGlass: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(26, 26, 46, 0.9)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 8,
    alignSelf: 'center',
  },
  topBarProfile: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.text,
  },
  // Profile dropdown
  profileDropdown: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 110 : 95,
    left: 40,
    right: 40,
    backgroundColor: COLORS.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    overflow: 'hidden',
    zIndex: 20,
  },
  profileOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  profileOptionActive: {
    backgroundColor: 'rgba(108, 92, 231, 0.1)',
  },
  profileOptionText: {
    fontSize: 15,
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  profileOptionTextActive: {
    color: COLORS.primary,
    fontWeight: '700',
  },
  // Bottom controls
  bottomControls: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingBottom: Platform.OS === 'ios' ? 100 : 80,
    paddingTop: 20,
    backgroundColor: 'rgba(10, 10, 26, 0.92)',
  },
  controlsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 40,
  },
  sideButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.glass,
    borderWidth: 1,
    borderColor: COLORS.glassBorder,
    justifyContent: 'center',
    alignItems: 'center',
  },
  captureButton: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  captureOuter: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4,
  },
  captureInner: {
    width: '100%',
    height: '100%',
    borderRadius: 36,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  captureInnerActive: {
    backgroundColor: COLORS.accent,
  },
  captureCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  // Result overlay
  resultOverlay: {
    ...(StyleSheet.absoluteFill as object),
    backgroundColor: 'rgba(10, 10, 26, 0.92)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  resultCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    paddingHorizontal: 32,
    paddingVertical: 40,
    alignItems: 'center',
    width: width - 48,
    maxWidth: 380,
  },
  resultIconBg: {
    width: 120,
    height: 120,
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  resultTitle: {
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 6,
  },
  resultName: {
    fontSize: 16,
    color: COLORS.textSecondary,
    fontWeight: '500',
    marginBottom: 28,
  },
  confidenceContainer: {
    width: '100%',
    marginBottom: 24,
  },
  confidenceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  confidenceLabel: {
    fontSize: 13,
    color: COLORS.textMuted,
    fontWeight: '600',
  },
  confidenceValue: {
    fontSize: 15,
    fontWeight: '800',
  },
  confidenceBarBg: {
    width: '100%',
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.surfaceLight,
    overflow: 'hidden',
  },
  confidenceBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  resultMeta: {
    flexDirection: 'row',
    gap: 24,
    marginBottom: 28,
  },
  resultMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  resultMetaText: {
    fontSize: 13,
    color: COLORS.textMuted,
  },
  resultDismissBtn: {
    backgroundColor: COLORS.surfaceLight,
    paddingVertical: 14,
    paddingHorizontal: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.glassBorder,
  },
  resultDismissText: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  resultRetryBtn: {
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    paddingHorizontal: 48,
    borderRadius: 14,
    marginBottom: 10,
  },
  resultRetryText: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.text,
  },
  resultActions: {
    gap: 8,
    width: '100%',
    alignItems: 'center',
  },
  distanceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 118, 117, 0.12)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    gap: 8,
    marginBottom: 28,
  },
  distanceBadgeText: {
    fontSize: 13,
    color: COLORS.danger,
    fontWeight: '600',
  },
  resultPhoto: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  photoResultIcon: {
    position: 'absolute',
    bottom: -4,
    right: 4,
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.surface,
  },
  thresholdInfoText: {
    fontSize: 11,
    color: COLORS.textMuted,
    marginTop: 6,
    textAlign: 'center',
  },
  // Error banner inline (reemplaza alertas nativas)
  errorBannerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(10, 10, 26, 0.88)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 90,
    paddingHorizontal: 24,
  },
  errorBannerCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 28,
    paddingVertical: 32,
    alignItems: 'center',
    width: '100%',
    maxWidth: 340,
  },
  errorBannerIconBg: {
    width: 72,
    height: 72,
    borderRadius: 36,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  errorBannerTitle: {
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
    textAlign: 'center',
  },
  errorBannerMessage: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  errorBannerRetryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 36,
    borderRadius: 14,
    gap: 8,
  },
  errorBannerRetryText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
});
